### ISSUE TITLE
data-raw: add amb country files for 2018/2019

### ISSUE THREAD

**Issue by fsolt** [fsolt/DCPOtools#28]

**Comment by fsolt** [comment]
@Tyhcass do the replication data really show the amb data up through 2018?  'Cause the file at <http://datasets.americasbarometer.org/database/files/2004-2018%20LAPOP%20AmericasBaometer%20Merge_FREE_V1.0_W.zip> only actually includes data through 2014, despite its name.  (To get the pre-merged dataset, one must pay $1500/year (see <https://www.vanderbilt.edu/lapop/become-subscriber.php>), which (a) I don't want to (and can't, tbh) do, and (b) I don't want to make anyone else do.)  Which means the latest data has to be added (both here and in e.g. mood_dem.csv) one country at a time after 2014.  I've already done this for the 2016/17 surveys, but not yet for the 2018/19 surveys.  So, again, to confirm, the latter really are in the replication data?

**Comment by Tyhcass** [comment]
@fsolt Thanks for reminding me. I double-checked the replication data and you are absolutely right! The data is up to 2014! I also double-checked the min and max years of other surveys to make sure we could have the same data to replicate.  
Thanks!

**Comment by fsolt** [comment]
Great, thanks.  I'll re-purpose this issue to make it for the country files for 2018/2019, which will be useful for other projects

**Comment by fsolt** [comment]
Also, per dcpo_dem_mood's issue on [Country-year crosswalks](https://github.com/fsolt/dcpo_dem_mood/issues/5):
- [ ] Argentina 2010
- [ ] Argentina 2012
- [ ] Argentina 2014
- [ ] Bolivia 2010
- [ ] Bolivia 2012
- [ ] Bolivia 2014
- [ ] Canada 2010
- [ ] Canada 2012
- [ ] Canada 2014
- [ ] Chile 2010
- [ ] Chile 2012
- [ ] Chile 2014
- [ ] Colombia 2005
- [ ] Colombia 2007
- [ ] Colombia 2009
- [ ] Colombia 2011
- [ ] Colombia 2013
- [ ] Ecuador 2014
- [ ] Haiti 2006
- [ ] Haiti 2008
- [ ] Haiti 2010
- [ ] Haiti 2012
- [ ] Haiti 2014
- [ ] Suriname 2010
- [ ] Suriname 2012
- [ ] Trinidad & Tobago 2010
- [ ] Trinidad & Tobago 2012
- [ ] US 2010
- [ ] US 2012
- [ ] US 2014

**Comment by Tyhcass** [comment]
@fsolt surveys_data only includes amb_haiti2016, we need
 Haiti 2006
 Haiti 2008
 Haiti 2010
 Haiti 2012
 Haiti 2014.

**Comment by fsolt** [comment]
These five surveys are in amb_combo, but were omitted from previous tries by a countrycode bug that I'm working on (#35)

**Comment by Tyhcass** [comment]
@fsolt all available amb_countries data in LAPOP website has been updated in dem_mood, including the latest ones in recent years which are not included in Claassen's data.

**Comment by fsolt** [comment]
Great, thanks--progress!

**Comment by Tyhcass** [comment]
@fsolt  When I list all of them, the problem seems not so severe.... Anyway, I list the date size difference here.  I omitted missing values and non-response, but still cannot his sample size. Actually, I think he just used the data size as his sample size without deleting any missing values or non-response.  That is why I am wondering maybe we should go back to your original approach. Sigh.

Differences in data size: 
                               DCPO         Claassen
 Argentina 2010:    1410         1200
 Argentina 2012:    1512        1200
 Argentina 2014:    1512        1200
 **Bolivia 2010:         3018        1200
 Bolivia 2012:         3029        1499**
 Bolivia 2014:         3066          3063
 Canada 2010:     1500         1500 
 Canada 2012:    1501          1501 
 Canada 2014:    1507          1507
 Chile 2010:        1965          1200
 Chile 2012:        1571          1500
 Chile 2014:        1571          1572
 Colombia 2005: 1487         1200
 Colombia 2007: 1491 	    1200
 Colombia 2009: 1493         1200
 Colombia 2011: 1503         1200
 Colombia 2013:  1511   	    1200
 Ecuador 2014:    1489        1489
 Haiti 2006:         1625  	    1625
 Haiti 2008:         1536         1536
 Haiti 2010:         1752         1752
 Haiti 2012:         1836         1500
 Haiti 2014:         1512         1512
 Suriname 2010:  1516        1516
 Suriname 2012:  1492        1501
 Trinidad & Tobago 2010: 1503 	1503
 Trinidad & Tobago 2012: 1506   	1500
 US 2010:             1500  	   1500
 US 2012:             1500  	   1500
 US 2014:             1500  	   1500
 Venezuela 2010:   1500 	   1200
 Venezuela 2012:   1500 	   1500
 **Venezuela 2014:   1500     2952**

**Comment by fsolt** [comment]
Hmm.  So the size differences go both directions.  Interesting.  Thanks, Cassandra.

Looking at Bolivia 2010, I see the percentages aren't really close either:
 
              w/ nonresponse | w/missing | Claassen
strong   .906                       .857                .861
church   .884                      .864                .683
threestate .811                    .756                .634

The file indicates it's v3 of the data.  We're just going to have to assume there have been some major revisions, footnote/appendix that this happened, and not worry about it too much.

**Comment by fsolt** [comment]
We're doing clearly doing our best.  (And as perfectionists, that's probably too much.)

**Comment by Tyhcass** [comment]
> Hmm. So the size differences go both directions. Interesting. Thanks, Cassandra.
> 
> Looking at Bolivia 2010, I see the percentages aren't really close either:
> 
> ```
>                     w/nonresponse | w/missing | Claassen
> ```
> 
> strong .906 .857 .861
> church .884 .864 .683
> threestate .811 .756 .634
> 
> The file indicates it's v3 of the data. We're just going to have to assume there have been some major revisions, footnote/appendix that this happened, and not worry about it too much.

En, really major revisions...  So,  double-check, will we continue using claassen_setup which incorporates non-response category or go back to the previous setup,, or both?  Since you have added missing data, I will setup Claassen data with the present approach soon and finish validation this week.

**Comment by fsolt** [comment]
I think we continue with `claassen_setup()` with nonresponse.  That is, after all, how the article says the data are handled.  We'll footnote that there are some differences in the data, possibly because the survey datasets have been updated, and also note that three of the surveys in the Dataverse spreadsheet don't exist.  This too may be the result of updates, but transcription errors are also a possibility.  We can even (probably should?) make a table in an appendix of all the discrepancies.

**Comment by Tyhcass** [comment]
Ha, I guess in the end our appendix will be longer than the main context.

**Comment by fsolt** [comment]
Not uncommon, but I'm not sure that'll be the case here.  But I still doubt this is going to seriously impact the estimates in many cases.  With regard to amb, for example, Lat Am is data rich--there are lots of other data.  I guess we'll see.

**Comment by sammo3182** [comment]
+1 for the footnote. As long as the outcomes are substantially consistent with Claassen, I don't think we should put too much effort to pursue the *exact same* data.

**Comment by fsolt** [comment]
> and also note that three of the surveys in the Dataverse spreadsheet don't exist.

[Four.](https://github.com/fsolt/dcpo_dem_mood/issues/5#issue-637892464)  Sigh.
